# Generated by Django 4.2.3 on 2023-07-31 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
